fixes, removal of deprecated functions, cleaning
 - adressing issues of https://github.com/puxplaying/toolbox/issues/7

diff --git a/bin/bcups b/bin/bcups
--- a/bin/bcups
+++ b/bin/bcups
@@ -3,8 +3,6 @@
 # =======================
 # Define Colors
 RED='\e[41m'
-BLUE='\e[44m'
-ORANGE='\e[46m'
 NC='\e[0m' # No color
 BG='\e[7m' # Highlighting Background color
 TC='\e[1m' # Highlighting Text color
@@ -33,13 +31,17 @@ SELECTDEFAULTSCANNERMSG="Searching for scanners... Select new default"
 IMGFILETYPECHOOSEMSG="Which filetype should be used? "
 NAMEFORSCANNEDFILEMSG="What name shall be given to the scanned file?"
 
-function pressanykeyrequest {
+# =======================
+# Pacman installation
+INSTALLPKGS="sudo pacman -Syu"
+
+function pressanykeyrequest() {
 	echo -e "$CONTINMSG"
 	read -r
 	STATUSVAR=1
 }
 
-function scanner_interface {
+function scanner_interface() {
 	if [ -e /usr/bin/xsane ]; then
 		xsane
 		STATUSVAR=$?
@@ -48,119 +50,119 @@ function scanner_interface {
 			echo "$XSANEINSTMSG"
 			STATUSVAR=$?
 		else
-			sudo pacman -Sy xsane && xsane
+			$INSTALLPKGS xsane && xsane
 			STATUSVAR=$?
 		fi
 	fi
-return $STATUSVAR
+	return $STATUSVAR
 }
 
-function webinterface {
-  $browser http://localhost:631
-  STATUSVAR=$?
-return $STATUSVAR
+function webinterface() {
+	$browser http://localhost:631
+	STATUSVAR=$?
+	return $STATUSVAR
 }
 
-function set_default_printer {
-  lpoptions -d $(echo $printers | fzf -e --reverse --prompt="$SELECTDEFAULTPRINTERMSG >")
-  STATUSVAR=$?
-  if [ $STATUSVAR -eq 0 ]; then
-  	echo ""
-  	echo ""
-  	echo "$DEFAULTPRINTERSETMSG"
-  fi
-return $STATUSVAR
+function set_default_printer() {
+	lpoptions -d $(echo $printers | fzf -e --reverse --prompt="$SELECTDEFAULTPRINTERMSG >")
+	STATUSVAR=$?
+	if [ $STATUSVAR -eq 0 ]; then
+		echo ""
+		echo ""
+		echo "$DEFAULTPRINTERSETMSG"
+	fi
+	return $STATUSVAR
 }
 
-function print_file {
-  grep -q "Default" ~/.cups/lpoptions && \
-  lpr $(fzf -m --reverse --prompt=" $SELECTFILESFORPRINTMSG >") || \
-  lpr -P $(echo $printers | fzf -e --reverse --prompt="$SELECTPRINTERTOUSEMSG >") $(fzf -m --reverse --prompt="$SELECTFILESFORPRINTINGMSG >")
-  STATUSVAR=$?
-  if [ $STATUSVAR -eq 0 ]; then
-  	echo ""
-  	echo ""
-  	echo "$PRINTINGMSG"
-  	sleep 3
-  fi
-return $STATUSVAR
+function print_file() {
+	grep -q "Default" ~/.cups/lpoptions &&
+		lpr $(fzf -m --reverse --prompt=" $SELECTFILESFORPRINTMSG >") ||
+		lpr -P $(echo $printers | fzf -e --reverse --prompt="$SELECTPRINTERTOUSEMSG >") $(fzf -m --reverse --prompt="$SELECTFILESFORPRINTINGMSG >")
+	STATUSVAR=$?
+	if [ $STATUSVAR -eq 0 ]; then
+		echo ""
+		echo ""
+		echo "$PRINTINGMSG"
+		sleep 3
+	fi
+	return $STATUSVAR
 }
 
-function select_scanner {
-  scanimage -L 2> /dev/null | fzf -e --reverse --prompt="$SEARCHINGSCANNERSMSG >" | awk '{print substr($2, 2, length($2) - 2)}'
-  STATUSVAR=$?
-return $STATUSVAR
+function select_scanner() {
+	scanimage -L 2>/dev/null | fzf -e --reverse --prompt="$SEARCHINGSCANNERSMSG >" | awk '{print substr($2, 2, length($2) - 2)}'
+	STATUSVAR=$?
+	return $STATUSVAR
 }
 
-function set_default_scanner {
-  default_scanner=$(scanimage -L 2> /dev/null | \
-  fzf -e --reverse --prompt="$SELECTDEFAULTSCANNERMSG >" | \
-  awk '{print $2} {print substr($2, 2, length($2) - 2)}')
-  STATUSVAR=$?
-  if [ $STATUSVAR -eq 0 ] && [ "$default_scanner" != "" ]; then
-  	echo "export SANE_DEFAULT_DEVICE=$default_scanner" >> $HOME/.profile
-  	SANE_DEFAULT_DEVICE="$default_scanner"
-  fi
-return $STATUSVAR
+function set_default_scanner() {
+	default_scanner=$(scanimage -L 2>/dev/null |
+		fzf -e --reverse --prompt="$SELECTDEFAULTSCANNERMSG >" |
+		awk '{print $2} {print substr($2, 2, length($2) - 2)}')
+	STATUSVAR=$?
+	if [ $STATUSVAR -eq 0 ] && [ "$default_scanner" != "" ]; then
+		echo "export SANE_DEFAULT_DEVICE=$default_scanner" >>$HOME/.profile
+		SANE_DEFAULT_DEVICE="$default_scanner"
+	fi
+	return $STATUSVAR
 }
 
-function select_filetype {
-PS3="$IMGFILETYPECHOOSEMSG"
-# Gather the results in an array.
-filetypes=("pnm" "tiff" "png" "jpeg")
+function select_filetype() {
+	PS3="$IMGFILETYPECHOOSEMSG"
+	# Gather the results in an array.
+	filetypes=("pnm" "tiff" "png" "jpeg")
 
-select pick in "${filetypes[@]}"
-do
-	case $pick in
-		*)	echo $pick
+	select pick in "${filetypes[@]}"; do
+		case $pick in
+		*)
+			echo $pick
 			break
-	esac
-done
+			;;
+		esac
+	done
 }
 
-function scan {
-  echo "$NAMEFORSCANNEDFILEMSG"
-  read filename
-  # check file name function needs
-  if [ "$filename" != "" ]; then
-  	eval filetype=$(select_filetype)
-  	if [ "$filetype" != "" ]; then
-  	  	scanner=$(select_scanner)
-  		if [ "$scanner" != "" ]; then
-  			scanimage -p -d $scanner --format=$filetype > $filename.$filetype
-  			STATUSVAR=$?
-  		else
-  			STATUSVAR=1
-  		fi
-  	else
-  		STATUSVAR=1
-  	fi
-  else
-  	STATUSVAR=1
-  fi
-return $STATUSVAR
+function scan() {
+	echo "$NAMEFORSCANNEDFILEMSG"
+	read filename
+	# check file name function needs
+	if [ "$filename" != "" ]; then
+		eval filetype=$(select_filetype)
+		if [ "$filetype" != "" ]; then
+			scanner=$(select_scanner)
+			if [ "$scanner" != "" ]; then
+				scanimage -p -d $scanner --format=$filetype >$filename.$filetype
+				STATUSVAR=$?
+			else
+				STATUSVAR=1
+			fi
+		else
+			STATUSVAR=1
+		fi
+	else
+		STATUSVAR=1
+	fi
+	return $STATUSVAR
 }
 
-function default_scan {
-  echo "$NAMEFORSCANNEDFILEMSG"
-  read filename
-  # check file name function needs
-  if [ "$filename" != "" ]; then
-  	eval filetype=$(select_filetype)
-  	if [ "$filetype" != "" ]; then
-  	  	scanimage -p --format=$filetype > $filename.$filetype
-  		STATUSVAR=$?
-  	else
-  		STATUSVAR=1
-  	fi
-  else
-  	STATUSVAR=1
-  fi
-return $STATUSVAR
+function default_scan() {
+	echo "$NAMEFORSCANNEDFILEMSG"
+	read filename
+	# check file name function needs
+	if [ "$filename" != "" ]; then
+		eval filetype=$(select_filetype)
+		if [ "$filetype" != "" ]; then
+			scanimage -p --format=$filetype >$filename.$filetype
+			STATUSVAR=$?
+		else
+			STATUSVAR=1
+		fi
+	else
+		STATUSVAR=1
+	fi
+	return $STATUSVAR
 }
 
-
-function main {
+function main() {
 
 	# Define Menu entries which will be run with the echo command
 	E0="\e[1mQ\e[0muit"
@@ -173,119 +175,119 @@ function main {
 	E7="List Scanners"
 	E8="Scan Using Defaults"
 
-    while true; do
-			printf '\33[H\33[2J' # Use this instead of the clear command
+	while true; do
+		printf '\33[H\33[2J' # Use this instead of the clear command
 
+		echo
+		echo -e "                       $BG$TC Printers and Scanners $NC"
+		echo -e " $TC+----------------------------------------------------------------+$NC"
+		echo -e " $TC|$NC    $BG 1 $NC $E1         $TC|$NC    $BG 2 $NC $E2            $TC|$NC"
+		echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
+		echo -e " $TC|$NC    $BG 3 $NC $E3     $TC|$NC    $BG 4 $NC $E4          $TC|$NC"
+		echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
+		echo -e " $TC|$NC    $BG 5 $NC $E5     $TC|$NC    $BG 6 $NC $E6          $TC|$NC"
+		echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
+		echo -e " $TC|$NC    $BG 7 $NC $E7 $NC          $TC|$NC    $BG 8 $NC $E8    $TC|$NC"
+		echo -e " $TC+----------------------------------------------------------------+$NC"
+		echo ""
+		echo -e "  Enter marked number             -    $BG 0 $NC $E0 "
+
+		# save entered number/letter in variable "choice"
+		read -r -n 1 -e choice
+
+		# test, whether "choice" fits any of the following numbers or letters
+		case "$choice" in
+
+		1)
 			echo
-			echo -e "                       $BG$TC Printers and Scanners $NC"
-			echo -e " $TC+----------------------------------------------------------------+$NC"
-			echo -e " $TC|$NC    $BG 1 $NC $E1         $TC|$NC    $BG 2 $NC $E2            $TC|$NC"
-			echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
-			echo -e " $TC|$NC    $BG 3 $NC $E3     $TC|$NC    $BG 4 $NC $E4          $TC|$NC"
-			echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
-			echo -e " $TC|$NC    $BG 5 $NC $E5     $TC|$NC    $BG 6 $NC $E6          $TC|$NC"
-			echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
-			echo -e " $TC|$NC    $BG 7 $NC $E7 $NC          $TC|$NC    $BG 8 $NC $E8    $TC|$NC"
-			echo -e " $TC+----------------------------------------------------------------+$NC"
-			echo ""
-			echo -e "  Enter marked number             -    $BG 0 $NC $E0 "
-
-			# save entered number/letter in variable "choice"
-    		read -r -n 1 -e choice
-
-			# test, whether "choice" fits any of the following numbers or letters
-			case "$choice" in
-
-        1)
-            echo
-            webinterface
-            STATUSVAR=$?
-            if [ $STATUSVAR -eq 0 ]; then
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        2)
-            echo
-            print_file
-            STATUSVAR=$?
-            if [ $STATUSVAR -eq 0 ]; then
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        3)
-            echo
-            set_scanner
-            STATUSVAR=$?
-            if [ $STATUSVAR -eq 0 ]; then
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        4)
-            echo
-            lpstat -p -d
-            STATUSVAR=$?
-            if [ $STATUSVAR -eq 0 ]; then
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        5)
-            echo
-            set_default_scanner
-            STATUSVAR=$?
-            if [ $STATUSVAR -eq 0 ]; then
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        6)
-            echo
-            scanner_inerface
-            STATUSVAR=$?
-            if [ $STATUSVAR -eq 0 ]; then
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        7)
-            echo
-            scanimage -L 2> /dev/null
-            STATUSVAR=$?
-            if [ $STATUSVAR -eq 0 ]; then
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        8)
-            echo
-            default_scan
-            STATUSVAR=$?
-            if [ $STATUSVAR -eq 0 ]; then
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-		0|Q|q)
-		    printf '\33[H\33[2J' && exit
-		    ;;
+			webinterface
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		2)
+			echo
+			print_file
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		3)
+			echo
+			set_scanner
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		4)
+			echo
+			lpstat -p -d
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		5)
+			echo
+			set_default_scanner
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		6)
+			echo
+			scanner_inerface
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		7)
+			echo
+			scanimage -L 2>/dev/null
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		8)
+			echo
+			default_scan
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		0 | Q | q)
+			printf '\33[H\33[2J' && exit
+			;;
 		*) # do this, if $choice variable contains anything else not offered above
-		    echo -e "$ERRORMSG"
-		    echo -e "$TRYAGAINMSG"
-		    sleep 2
-		    ;;
-    esac
-    done
+			echo -e "$ERRORMSG"
+			echo -e "$TRYAGAINMSG"
+			sleep 2
+			;;
+		esac
+	done
 }
 
 main
diff --git a/bin/initmenu b/bin/initmenu
--- a/bin/initmenu
+++ b/bin/initmenu
@@ -3,11 +3,11 @@
 # =======================
 # Define Colors
 RED='\e[41m'
-BLUE='\e[44m'
-ORANGE='\e[46m'
 NC='\e[0m' # No color
 BG='\e[7m' # Highlighting Background color
 TC='\e[1m' # Highlighting Text color
+
+TEXTEDITOR=$EDITOR
 
 # =======================
 # Service messages section
@@ -24,61 +24,60 @@ SERVICEENABLEDMSG=" was enabled successfully"
 SERVICESTOPPEDMSG=" was stopped successfully"
 SERVICEDISABLEDMSG=" was disabled successfully"
 
-function pressanykeyrequest {
+function pressanykeyrequest() {
 	echo -e "$CONTINMSG"
 	read -r
 	STATUSVAR=1
 }
 
-function config_editor {
-PS3="$SELECTFILEMSG"
-configs=("journald.conf" "system.conf" "logind.conf" "user.conf" "cancel")
+function config_editor() {
+	PS3="$SELECTFILEMSG"
+	configs=("journald.conf" "system.conf" "logind.conf" "user.conf" "cancel")
 
-select pick in "${configs[@]}"
-do
-	case $pick in
+	select pick in "${configs[@]}"; do
+		case $pick in
 		logind.conf)
-			[ -e /etc/systemd/logind.conf.d/10-logind.conf ] || \
-			sudo mkdir -p /etc/systemd/logind.conf.d/ && \
-			sudo cp /etc/systemd/logind.conf /etc/systemd/logind.conf.d/10-logind.conf && \
-			sudo $TEXTEDITOR /etc/systemd/logind.conf.d/10-logind.conf
+			[ -e /etc/systemd/logind.conf.d/10-logind.conf ] ||
+				sudo mkdir -p /etc/systemd/logind.conf.d/ &&
+				sudo cp /etc/systemd/logind.conf /etc/systemd/logind.conf.d/10-logind.conf &&
+				sudo "$TEXTEDITOR" /etc/systemd/logind.conf.d/10-logind.conf
 			break
 			;;
 		system.conf)
-			[ -e /etc/systemd/system.conf.d/10-system.conf ] || \
-			sudo mkdir -p /etc/systemd/system.conf.d/ && \
-			sudo cp /etc/systemd/system.conf /etc/systemd/system.conf.d/10-system.conf && \
-			sudo $TEXTEDITOR /etc/systemd/system.conf.d/10-system.conf
+			[ -e /etc/systemd/system.conf.d/10-system.conf ] ||
+				sudo mkdir -p /etc/systemd/system.conf.d/ &&
+				sudo cp /etc/systemd/system.conf /etc/systemd/system.conf.d/10-system.conf &&
+				sudo "$TEXTEDITOR" /etc/systemd/system.conf.d/10-system.conf
 			break
 			;;
 		journald.conf)
-			[ -e /etc/systemd/journald.conf.d/10-journald.conf ] || \
-			sudo mkdir -p /etc/systemd/journald.conf.d/ && \
-			sudo cp /etc/systemd/journald.conf /etc/systemd/journald.conf.d/10-journald.conf && \
-			sudo $TEXTEDITOR /etc/systemd/journald.conf.d/10-journald.conf
+			[ -e /etc/systemd/journald.conf.d/10-journald.conf ] ||
+				sudo mkdir -p /etc/systemd/journald.conf.d/ &&
+				sudo cp /etc/systemd/journald.conf /etc/systemd/journald.conf.d/10-journald.conf &&
+				sudo "$TEXTEDITOR" /etc/systemd/journald.conf.d/10-journald.conf
 			break
 			;;
 		user.conf)
-			[ -e /etc/systemd/user.conf.d/10-user.conf ] || \
-			sudo mkdir -p /etc/systemd/user.conf.d/ && \
-			sudo cp /etc/systemd/user.conf /etc/systemd/user.conf.d/10-user.conf && \
-			sudo $TEXTEDITOR /etc/systemd/user.conf.d/10-user.conf
+			[ -e /etc/systemd/user.conf.d/10-user.conf ] ||
+				sudo mkdir -p /etc/systemd/user.conf.d/ &&
+				sudo cp /etc/systemd/user.conf /etc/systemd/user.conf.d/10-user.conf &&
+				sudo "$TEXTEDITOR" /etc/systemd/user.conf.d/10-user.conf
 			break
 			;;
 		cancel)
 			break
-	esac
-done
+			;;
+		esac
+	done
 
 }
 
-function change_runlevel {
-PS3="$SELECTTARGETMSG"
-targets=("poweroff" "rescue" "multi-user" "graphical" "reboot" "cancel")
+function change_runlevel() {
+	PS3="$SELECTTARGETMSG"
+	targets=("poweroff" "rescue" "multi-user" "graphical" "reboot" "cancel")
 
-select pick in "${targets[@]}"
-do
-	case $pick in
+	select pick in "${targets[@]}"; do
+		case $pick in
 		poweroff)
 			sudo systemctl isolate poweroff.target
 			break
@@ -101,65 +100,61 @@ do
 			;;
 		cancel)
 			break
-	esac
-done
-
+			;;
+		esac
+	done
 
 }
 
-function enable_services {
+function enable_services() {
 	OUTPUTITEM=""
 	OUTPUTITEM=$(systemctl list-unit-files | awk '/disabled/ {print $1}' | fzf -m -e --reverse)
-	if [ "$OUTPUTITEM" != "" ]
-	then
-		sudo systemctl enable $OUTPUTITEM
+	if [ "$OUTPUTITEM" != "" ]; then
+		sudo systemctl enable "$OUTPUTITEM"
 		STATUSVAR=$?
 	else
 		STATUSVAR=1
 	fi
-return $STATUSVAR
+	return $STATUSVAR
 }
 
-function start_services {
+function start_services() {
 	OUTPUTITEM=""
 	OUTPUTITEM=$(systemctl list-unit-files | awk '/disabled/ {print $1}' | fzf -m -e --reverse)
-	if [ "$OUTPUTITEM" != "" ]
-	then
-		sudo systemctl start $OUTPUTITEM
+	if [ "$OUTPUTITEM" != "" ]; then
+		sudo systemctl start "$OUTPUTITEM"
 		STATUSVAR=$?
 	else
 		STATUSVAR=1
 	fi
-return $STATUSVAR
+	return $STATUSVAR
 }
 
-function stop_services {
+function stop_services() {
 	OUTPUTITEM=""
 	OUTPUTITEM=$(systemctl list-unit-files | awk '/enabled/ {print $1}' | fzf -m -e --reverse)
-	if [ "$OUTPUTITEM" != "" ]
-	then
-		sudo systemctl stop $OUTPUTITEM
+	if [ "$OUTPUTITEM" != "" ]; then
+		sudo systemctl stop "$OUTPUTITEM"
 		STATUSVAR=$?
 	else
 		STATUSVAR=1
 	fi
-return $STATUSVAR
+	return $STATUSVAR
 }
 
-function disable_services {
+function disable_services() {
 	OUTPUTITEM=""
 	OUTPUTITEM=$(systemctl list-unit-files | awk '/enabled/ {print $1}' | fzf -m -e --reverse)
-	if [ "$OUTPUTITEM" != "" ]
-	then
-		sudo systemctl disable $OUTPUTITEM
+	if [ "$OUTPUTITEM" != "" ]; then
+		sudo systemctl disable "$OUTPUTITEM"
 		STATUSVAR=$?
 	else
 		STATUSVAR=1
 	fi
-return $STATUSVAR
+	return $STATUSVAR
 }
 
-function main {
+function main() {
 
 	# Define Menu entries which will be run with the echo command
 	E0="\e[1mQ\e[0muit"
@@ -173,115 +168,115 @@ function main {
 	E8="Change Runlevel"
 	E9="Analyze Boot"
 
-    while true; do
+	while true; do
 
-    printf '\33[H\33[2J' # Use this instead of the clear command
+		printf '\33[H\33[2J' # Use this instead of the clear command
 
 		echo
-    echo -e "                            $BG$TC Init-System $NC"
-    echo -e " $TC+----------------------------------------------------------------+$NC"
-    echo -e " $TC|$NC    $BG 1 $NC $E1         $TC|$NC    $BG 2 $NC $E2       $TC|$NC"
-    echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
-    echo -e " $TC|$NC    $BG 3 $NC $E3          $TC|$NC    $BG 4 $NC $E4          $TC|$NC"
-    echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
-    echo -e " $TC|$NC    $BG 5 $NC $E5    $TC|$NC    $BG 6 $NC $E6     $TC|$NC"
-    echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
-    echo -e " $TC|$NC    $BG 7 $NC $E7 $NC      $TC|$NC    $BG 8 $NC $E8        $TC|$NC"
-    echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
-    echo -e " $TC|$NC    $BG 9 $NC $E9 	          $TC|$NC    $BG$TC T $NC$BG$TC O $NC$BG$TC O $NC$BG$TC L $NC $BG B $NC $BG O $NC $BG X $NC $E12  $TC|$NC"
-    echo -e " $TC+----------------------------------------------------------------+$NC"
-    echo ""
-    echo -e "  Enter marked number             -    $BG 0 $NC $E0 "
+		echo -e "                            $BG$TC Init-System $NC"
+		echo -e " $TC+----------------------------------------------------------------+$NC"
+		echo -e " $TC|$NC    $BG 1 $NC $E1         $TC|$NC    $BG 2 $NC $E2       $TC|$NC"
+		echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
+		echo -e " $TC|$NC    $BG 3 $NC $E3          $TC|$NC    $BG 4 $NC $E4          $TC|$NC"
+		echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
+		echo -e " $TC|$NC    $BG 5 $NC $E5    $TC|$NC    $BG 6 $NC $E6     $TC|$NC"
+		echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
+		echo -e " $TC|$NC    $BG 7 $NC $E7 $NC      $TC|$NC    $BG 8 $NC $E8        $TC|$NC"
+		echo -e " $TC|$NC--------------------------------$TC|$NC-------------------------------$TC|$NC"
+		echo -e " $TC|$NC    $BG 9 $NC $E9 	          $TC|$NC    $BG$TC T $NC$BG$TC O $NC$BG$TC O $NC$BG$TC L $NC $BG B $NC $BG O $NC $BG X $NC $E12  $TC|$NC"
+		echo -e " $TC+----------------------------------------------------------------+$NC"
+		echo ""
+		echo -e "  Enter marked number             -    $BG 0 $NC $E0 "
 
-    # save entered number/letter in variable "choice"
-    read -r -n 1 -e choice
+		# save entered number/letter in variable "choice"
+		read -r -n 1 -e choice
 
-    # test, whether "choice" fits any of the following numbers or letters
-    case "$choice" in
+		# test, whether "choice" fits any of the following numbers or letters
+		case "$choice" in
 
-        1)
-            echo
-            enable_services
-            STATUSVAR=$?
-	    	if [ $STATUSVAR -eq 0 ]; then
-		    	echo -e "$SERVICEPREFIXMSG$OUTPUTITEM$SERVICEENABLEDMSG"
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        2)
-            echo
-            disable_services
-            STATUSVAR=$?
-	    	if [ $STATUSVAR -eq 0 ]; then
-		    	echo -e "$SERVICEPREFIXMSG$OUTPUTITEM$SERVICEDISABLEDMSG"
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-            ;;
-        3)
-            echo
-            start_services
-            STATUSVAR=$?
-	    	if [ $STATUSVAR -eq 0 ]; then
-		    	echo -e "$SERVICEPREFIXMSG$OUTPUTITEM$SERVICESTARTEDMSG"
-		    	pressanykeyrequest
-	    	else
-		    	echo""
-	    	fi
-            ;;
-        4)
-            echo
-            stop_services
-            STATUSVAR=$?
-	    	if [ $STATUSVAR -eq 0 ]; then
-		    	echo -e "$SERVICEPREFIXMSG$OUTPUTITEM$SERVICESTOPPEDMSG"
-		    	pressanykeyrequest
-	    	else
-		    	echo ""
-	    	fi
-	    	;;
-        5)
-            echo
-            systemctl
-            echo ""
-            pressanykeyrequest
-            ;;
-        6)
-            echo
-            sudo dmesg
-            echo ""
-            pressanykeyrequest
-            ;;
-        7)
-            echo
-            config_editor
-            echo ""
-            ;;
-        8)
-            echo
-            change_runlevel
-            echo ""
-            ;;
-        9)
-            echo
-	    	clear
-            systemd-analyze blame
-            echo ""
-            pressanykeyrequest
-            ;;
-		0|Q|q)
-		    printf '\33[H\33[2J' && exit
-		    ;;
+		1)
+			echo
+			enable_services
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				echo -e "$SERVICEPREFIXMSG$OUTPUTITEM$SERVICEENABLEDMSG"
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		2)
+			echo
+			disable_services
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				echo -e "$SERVICEPREFIXMSG$OUTPUTITEM$SERVICEDISABLEDMSG"
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		3)
+			echo
+			start_services
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				echo -e "$SERVICEPREFIXMSG$OUTPUTITEM$SERVICESTARTEDMSG"
+				pressanykeyrequest
+			else
+				echo""
+			fi
+			;;
+		4)
+			echo
+			stop_services
+			STATUSVAR=$?
+			if [ $STATUSVAR -eq 0 ]; then
+				echo -e "$SERVICEPREFIXMSG$OUTPUTITEM$SERVICESTOPPEDMSG"
+				pressanykeyrequest
+			else
+				echo ""
+			fi
+			;;
+		5)
+			echo
+			systemctl
+			echo ""
+			pressanykeyrequest
+			;;
+		6)
+			echo
+			sudo dmesg
+			echo ""
+			pressanykeyrequest
+			;;
+		7)
+			echo
+			config_editor
+			echo ""
+			;;
+		8)
+			echo
+			change_runlevel
+			echo ""
+			;;
+		9)
+			echo
+			clear
+			systemd-analyze blame
+			echo ""
+			pressanykeyrequest
+			;;
+		0 | Q | q)
+			printf '\33[H\33[2J' && exit
+			;;
 		*) # do this, if $choice variable contains anything else not offered above
-		    echo -e "$ERRORMSG"
-		    echo -e "$TRYAGAINMSG"
-		    sleep 2
-		    ;;
-    esac
-    done
+			echo -e "$ERRORMSG"
+			echo -e "$TRYAGAINMSG"
+			sleep 2
+			;;
+		esac
+	done
 }
 
 main
diff --git a/bin/mhwd-tui b/bin/mhwd-tui
--- a/bin/mhwd-tui
+++ b/bin/mhwd-tui
@@ -3,8 +3,6 @@
 # =======================
 # Define Colors
 RED='\e[41m'
-BLUE='\e[44m'
-ORANGE='\e[46m'
 NC='\e[0m' # No color
 BG='\e[7m' # Highlighting Background color
 TC='\e[1m' # Highlighting Text color
@@ -16,8 +14,12 @@ ERRORMSG="$RED Wrong option $NC"
 TRYAGAINMSG=" Please try again..."
 
 # =======================
+# Pacman installation
+INSTALLPKGS="sudo pacman -Syu"
+
+# =======================
 # mhwd-ui functions
-cd
+cd || exit
 trap 'rm $HOME/{.running_kernel,.installed_kernels,.available_kernels}' EXIT
 in_array() {
     local haystack=${1}[@]
@@ -30,69 +32,69 @@ in_array() {
     return 1
 }
 
-function install_kernel {
-PS3="which kernel do you wish to install? (press ctrl+d to preceed, ctrl+c to cancel): "
-# Gather the results in an array.
-kernels=($(grep -v -f .installed_kernels .available_kernels) "proceed" "cancel")
+function install_kernel() {
+    PS3="which kernel do you wish to install? (press ctrl+d to preceed, ctrl+c to cancel): "
+    # Gather the results in an array.
+    kernels=($(grep -v -f .installed_kernels .available_kernels) "proceed" "cancel")
 
-select pick in "${kernels[@]}"
-do
-	case $pick in
-		proceed)
-			break
-			;;
-		cancel)
-			exit
-			;;
-		*)	if in_array picks $pick; then
-					picks=($(printf -- '%s\n' "${picks[@]}" | grep -v $pick));
-				else
-					picks+=("$pick")
-			fi
-	        printf 'Selected: %s\n' "${picks[*]}"
-			;;
-	esac
-done
+    select pick in "${kernels[@]}"; do
+        case $pick in
+        proceed)
+            break
+            ;;
+        cancel)
+            exit
+            ;;
+        *)
+            if in_array picks $pick; then
+                picks=($(printf -- '%s\n' "${picks[@]}" | grep -v $pick))
+            else
+                picks+=("$pick")
+            fi
+            printf 'Selected: %s\n' "${picks[*]}"
+            ;;
+        esac
+    done
 
-if [[ $picks ]]; then
-    printf 'Installing %s\n' "${picks[*]}"
-    sudo mhwd-kernel -i "${picks[@]}"
-fi
+    if [[ $picks ]]; then
+        printf 'Installing %s\n' "${picks[*]}"
+        sudo mhwd-kernel -i "${picks[@]}"
+    fi
 }
 
-function remove_kernel {
-PS3="which kernel do you wish to remove? (press ctrl+d to preceed, ctrl+c to cancel): "
-# Gather the results in an array.
-kernels=($(grep -v -f .running_kernel .installed_kernels) "proceed" "cancel")
+function remove_kernel() {
+    PS3="which kernel do you wish to remove? (press ctrl+d to preceed, ctrl+c to cancel): "
+    # Gather the results in an array.
+    kernels=($(grep -v -f .running_kernel .installed_kernels) "proceed" "cancel")
 
-select pick in "${kernels[@]}"
-do
-	case $pick in
-		proceed)
-			break
-			;;
-		cancel)
-			exit
-			;;
-		*)	if in_array picks $pick; then
-					picks=($(printf -- '%s\n' "${picks[@]}" | grep -v $pick));
-				else
-					picks+=("$pick")
-			fi
-	        printf 'Selected: %s\n' "${picks[*]}"
-			;;
-	esac
-done
+    select pick in "${kernels[@]}"; do
+        case $pick in
+        proceed)
+            break
+            ;;
+        cancel)
+            exit
+            ;;
+        *)
+            if in_array picks $pick; then
+                picks=($(printf -- '%s\n' "${picks[@]}" | grep -v $pick))
+            else
+                picks+=("$pick")
+            fi
+            printf 'Selected: %s\n' "${picks[*]}"
+            ;;
+        esac
+    done
 
-if [[ $picks ]]; then
-    printf 'Removing %s\n' "${picks[*]}"
-    sudo mhwd-kernel -r "${picks[@]}"
-fi
+    if [[ $picks ]]; then
+        printf 'Removing %s\n' "${picks[*]}"
+        sudo mhwd-kernel -r "${picks[@]}"
+    fi
 }
 
-mhwd-kernel -li | awk 'NR==1 {print $4}' | tr -d '()' > .running_kernel &
-mhwd-kernel -li | awk 'NR > 2 { print $2}' > .installed_kernels &
-mhwd-kernel -l | awk 'NR > 1 { print $2}' > .available_kernels &
+mhwd-kernel -li | awk 'NR==1 {print $4}' | tr -d '()' >.running_kernel &
+mhwd-kernel -li | awk 'NR > 2 { print $2}' >.installed_kernels &
+mhwd-kernel -l | awk 'NR > 1 { print $2}' >.available_kernels &
 
 # Define Menu entries which will be run with the echo command
 E0="\e[1mQ\e[0muit"
@@ -109,10 +111,8 @@ E10="\e[1mB\e[0mios Information"
 E11="P\e[1mo\e[0mwer Consumption"
 E12="\e[1mP\e[0mrinters"
 
-
 # Run infinite loop for UI / menu, till the user quits using the "quit" option or CTRL+C.
-while true
-do
+while true; do
 
     printf '\33[H\33[2J' # Use this instead of the clear command
 
@@ -139,107 +139,104 @@ do
 
     # test, whether "choice" fits any of the following numbers or letters
     case "$choice" in
-        1|I|i)
-            printf '\33[H\33[2J'
-            install_kernel
-            echo ""
-            ;;
-        2|R|r)
-            printf '\33[H\33[2J'
-            remove_kernel
-            echo ""
-            ;;
-        3|F|f)
-            printf '\33[H\33[2J'
-            sudo mhwd -a pci free 0300
-            echo
-            echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
-            # wait for input, e.g. by pressing ENTER:
-            read -r
-            ;;
-        4|N|n)
-            printf '\33[H\33[2J'
-            sudo mhwd -a pci nonfree 0300
-            echo
-            echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
-            # wait for input, e.g. by pressing ENTER:
-            read -r
-            ;;
-        5|L|l)
-            printf '\33[H\33[2J'
-            mhwd -li -d
-            echo
-            echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
-            # wait for input, e.g. by pressing ENTER:
-            read -r
-            ;;
-        6|C|c)
-            printf '\33[H\33[2J'
-            xinput_tui
-            ;;
-        7|S|s)
-            printf '\33[H\33[2J'
-            sensors
-            echo
-            echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
-            # wait for input, e.g. by pressing ENTER:
-            read -r
-            ;;
-        8|D|d)
-            printf '\33[H\33[2J'
-            ncdu -x /
-            echo
-            echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
-            # wait for input, e.g. by pressing ENTER:
-            read -r
-            ;;
-        9|H|h)
-            printf '\33[H\33[2J'
-            ncdu -x $HOME
-            echo
-            echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
-            # wait for input, e.g. by pressing ENTER:
-            read -r
-            ;;
-        B|b)
-            printf '\33[H\33[2J'
-            sudo dmidecode -t bios
-            echo
-            echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
-            # wait for input, e.g. by pressing ENTER:
-            read -r
-            ;;
-        O|o)
-            printf '\33[H\33[2J'
-            if [[ -f /usr/bin/powertop ]]
-            then
+    1 | I | i)
+        printf '\33[H\33[2J'
+        install_kernel
+        echo ""
+        ;;
+    2 | R | r)
+        printf '\33[H\33[2J'
+        remove_kernel
+        echo ""
+        ;;
+    3 | F | f)
+        printf '\33[H\33[2J'
+        sudo mhwd -a pci free 0300
+        echo
+        echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
+        # wait for input, e.g. by pressing ENTER:
+        read -r
+        ;;
+    4 | N | n)
+        printf '\33[H\33[2J'
+        sudo mhwd -a pci nonfree 0300
+        echo
+        echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
+        # wait for input, e.g. by pressing ENTER:
+        read -r
+        ;;
+    5 | L | l)
+        printf '\33[H\33[2J'
+        mhwd -li -d
+        echo
+        echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
+        # wait for input, e.g. by pressing ENTER:
+        read -r
+        ;;
+    6 | C | c)
+        printf '\33[H\33[2J'
+        xinput_tui
+        ;;
+    7 | S | s)
+        printf '\33[H\33[2J'
+        sensors
+        echo
+        echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
+        # wait for input, e.g. by pressing ENTER:
+        read -r
+        ;;
+    8 | D | d)
+        printf '\33[H\33[2J'
+        ncdu -x /
+        echo
+        echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
+        # wait for input, e.g. by pressing ENTER:
+        read -r
+        ;;
+    9 | H | h)
+        printf '\33[H\33[2J'
+        ncdu -x $HOME
+        echo
+        echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
+        # wait for input, e.g. by pressing ENTER:
+        read -r
+        ;;
+    B | b)
+        printf '\33[H\33[2J'
+        sudo dmidecode -t bios
+        echo
+        echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
+        # wait for input, e.g. by pressing ENTER:
+        read -r
+        ;;
+    O | o)
+        printf '\33[H\33[2J'
+        if [[ -f /usr/bin/powertop ]]; then
             sudo powertop
-            else
+        else
             echo "Installing Powertop"
-            if [[ -f /var/lib/pacman/db.lck ]]
-            then
-            echo "powertop is not installed and Pacman seems to be in use"
+            if [[ -f /var/lib/pacman/db.lck ]]; then
+                echo "powertop is not installed and Pacman seems to be in use"
             else
-            sudo pacman -Sy powertop && sudo powertop
+                $INSTALLPKGS powertop && sudo powertop
             fi
-            fi
-            echo
-            echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
-            # wait for input, e.g. by pressing ENTER:
-            read -r
-            ;;
-        P|p)
-            printf '\33[H\33[2J'
-            bcups
-            ;;
-        0|Q|q)
-            printf '\33[H\33[2J' && exit
-            ;;
-        *) # do this, if $choice variable contains anything else not offered above
-            echo -e "$ERRORMSG"
-            echo -e "$TRYAGAINMSG"
-            sleep 2
-            ;;
+        fi
+        echo
+        echo -e " $RED To return to Hardware and Drivers press ENTER $NC"
+        # wait for input, e.g. by pressing ENTER:
+        read -r
+        ;;
+    P | p)
+        printf '\33[H\33[2J'
+        bcups
+        ;;
+    0 | Q | q)
+        printf '\33[H\33[2J' && exit
+        ;;
+    *) # do this, if $choice variable contains anything else not offered above
+        echo -e "$ERRORMSG"
+        echo -e "$TRYAGAINMSG"
+        sleep 2
+        ;;
     esac
-    done
-fi
+done
